#!/usr/bin/env bash

echoerr() {
	1>&2 echo aurclean: "$@"
}

for package in "$@"; do
	echoerr "Cleaning up $package..."
	cd "${AUR_DIR:-$HOME/.aur}/$package" || { echoerr Aborting.; break; }
	git clean -fxfd || { echoerr Aborting.; break; }
done
