#!/usr/bin/env bash

echoerr() {
  1>&2 echo aurinstall: "$@"
}

pager() {
  if [[ -n $PAGER ]]; then
    "$PAGER" "$@"
  else
    # use -K flag to allow aborting with CTRL-C
    less -K "$@"
  fi
}

packages=()
asdeps=0

for arg in "$@"; do
  if [[ $arg == '--asdeps' ]]; then
    asdeps=1
  else
    packages+=("$arg")
  fi
done

for package in "${packages[@]}"; do
  echoerr "Installing $package..."
  cd "${AUR_DIR:-$HOME/Downloads/AUR}/$package" || { echoerr Aborting.; break; }

  echoerr Inspecting PKGBUILD...
  pager PKGBUILD || { echoerr Aborting.; break; }

  echoerr Running makepkg...
  if ((asdeps)); then
    echoerr --asdeps flag provided. Installing as dependency...
    makepkg -sic --asdeps
  else
    makepkg -sic
  fi
done
