#!/usr/bin/env bash

nocolor=0
quiet=0
keywords=()

# do not emit color codes if stdout is not a tty
! [[ -t 1 ]] && nocolor=1

while (( $# )); do
	case $1 in
		-C|--no-color)
			nocolor=1
			;;
		-q|--quiet)
			quiet=1
			;;
		*)
			keywords+=("$1")
	esac
	shift
done

jqprog='.results | sort_by(.Name) |
	map(.Name + ";" + .Version + ";" + .Description) | .[]'

curl -s "https://aur.archlinux.org/rpc/?v=5&type=search&arg=${keywords[*]}" |
	jq -r "$jqprog" |
	while IFS=';' read -r name version description; do
		if (( $quiet )); then
			printf '%s\n' "$name"
		elif (( $nocolor )); then
			printf '%s %s\n    %s\n' "$name" "$version" "$description"
		else
			bold=$(tput bold)
			normal=$(tput sgr0)
			green=$(tput setaf 2)

			printf '%s%s %s%s%s\n    %s\n' \
				"$bold" "$name" "$green" "$version" "$normal" \
				"$description"
		fi
	done
